### ISSUE TITLE
Add product tags with tooltip and link

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/code.quarkus.redhat.com#2]
@tqvarnst could you provide the list of labels, tooltip and link for all the product tags please.

**Comment by ia3andy** [comment]
Links:
- dev-support: https://access.redhat.com/support/offerings/developer/soc/
- supported: https://access.redhat.com/support/offerings/production/soc/
- tech-preview: TBD
- deprecated: "This feature is likely to be replaced or removed in a future version of Red Hat build of Quarkus. See release notes on docs.redhat.com for more information"

**Comment by tqvarnst** [comment]
Here is my suggestions: "Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process. However, these features are not fully supported under Red Hat Subscription Level Agreements."
